package IoC;

/**
 *
 * @author Ignacio_Gonzalez
 */
public class JefeEmpleado implements Empleado {

    private CreacionInformes newInforme;

    public void setNewInforme(CreacionInformes newInforme) {
        this.newInforme = newInforme;
    }
    
    @Override
    public String getTasks() {
        return "Hi pal, I am one of the bosses";
    }

    @Override
    public String getInforme() {
       return "This is a report generated by the boss: "+ newInforme.getInforme();
    }
}
