/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IoC;

/**
 *
 * @author Ignacio_Gonzalez
 */
class SecretarioEmpleado implements Empleado {
    
    private CreacionInformes informeNuevo;

    public void setInformeNuevo(CreacionInformes informeNuevo) {
        this.informeNuevo = informeNuevo;
    }

    @Override
    public String getTasks() {
        return "Hi pal, I am a secretary, welcome to my world";
    }

    @Override
    public String getInforme() {
        return "Report generated by the secretary: "+ informeNuevo.getInforme();
    }

}
